package com.pv207.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Offer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("category")
	private java.lang.String category;
	@org.kie.api.definition.type.Label("price")
	private java.lang.Long price;
	@org.kie.api.definition.type.Label("location")
	private java.lang.String location;
	@org.kie.api.definition.type.Label("description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("dateFrom")
	private java.time.LocalDate dateFrom;
	@org.kie.api.definition.type.Label("dateTo")
	private java.time.LocalDate dateTo;

	public Offer() {
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.Long getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Long price) {
		this.price = price;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.time.LocalDate getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(java.time.LocalDate dateFrom) {
		this.dateFrom = dateFrom;
	}

	public java.time.LocalDate getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(java.time.LocalDate dateTo) {
		this.dateTo = dateTo;
	}

	public Offer(java.lang.String category, java.lang.Long price,
			java.lang.String location, java.lang.String description,
			java.time.LocalDate dateFrom, java.time.LocalDate dateTo) {
		this.category = category;
		this.price = price;
		this.location = location;
		this.description = description;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
	}
	
	@Override
	public String toString() {
	    return "category="+this.category+";price="+this.price+";location="+this.location+";description="+this.description+";dateFrom="+this.dateFrom+";dateTo="+this.dateTo;
	}

}