package com.pv207.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class PhotographersSelect implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> photographers;

	public PhotographersSelect() {
	}

	public java.util.List<java.lang.String> getPhotographers() {
		return this.photographers;
	}

	public void setPhotographers(java.util.List<java.lang.String> photographers) {
		this.photographers = photographers;
	}

	public PhotographersSelect(java.util.List<java.lang.String> photographers) {
		this.photographers = photographers;
	}

}