package com.pv207.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class PhotographerOrderData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String photographer;
	private java.lang.String day;
	private java.lang.Integer price;
	private java.lang.Integer rating;

	private java.lang.String phone;

	private java.lang.String email;

	public PhotographerOrderData() {
	}

	public java.lang.String getPhotographer() {
		return this.photographer;
	}

	public void setPhotographer(java.lang.String photographer) {
		this.photographer = photographer;
	}

	public java.lang.String getDay() {
		return this.day;
	}

	public void setDay(java.lang.String day) {
		this.day = day;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public java.lang.Integer getRating() {
		return this.rating;
	}

	public void setRating(java.lang.Integer rating) {
		this.rating = rating;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public PhotographerOrderData(java.lang.String photographer,
			java.lang.String day, java.lang.Integer price,
			java.lang.Integer rating, java.lang.String phone,
			java.lang.String email) {
		this.photographer = photographer;
		this.day = day;
		this.price = price;
		this.rating = rating;
		this.phone = phone;
		this.email = email;
	}

}