package com.pv207.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class PhotographerDatesSelect implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> dates;

	public PhotographerDatesSelect() {
	}

	public java.util.List<java.lang.String> getDates() {
		return this.dates;
	}

	public void setDates(java.util.List<java.lang.String> dates) {
		this.dates = dates;
	}

	public PhotographerDatesSelect(java.util.List<java.lang.String> dates) {
		this.dates = dates;
	}

}