package com.pv207.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class PhotographerForm implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ico")
	private java.lang.String ico;
	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("web")
	private java.lang.String web;

	public PhotographerForm() {
	}

	public java.lang.String getIco() {
		return this.ico;
	}

	public void setIco(java.lang.String ico) {
		this.ico = ico;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getWeb() {
		return this.web;
	}

	public void setWeb(java.lang.String web) {
		this.web = web;
	}

	public PhotographerForm(java.lang.String ico, java.lang.String email,
			java.lang.String name, java.lang.String web) {
		this.ico = ico;
		this.email = email;
		this.name = name;
		this.web = web;
	}

}