package com.pv207.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Registration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("City")
	private java.lang.String city;
	@org.kie.api.definition.type.Label("Street")
	private java.lang.String street;
	@org.kie.api.definition.type.Label("Email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Surname")
	private java.lang.String surname;
	@org.kie.api.definition.type.Label("Password")
	private java.lang.String password;
	@org.kie.api.definition.type.Label("Phone")
	private java.lang.String phone;
	@org.kie.api.definition.type.Label("Sex")
	private java.lang.String sex;

	public Registration() {
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getStreet() {
		return this.street;
	}

	public void setStreet(java.lang.String street) {
		this.street = street;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public java.lang.String getPassword() {
		return this.password;
	}

	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getSex() {
		return this.sex;
	}

	public void setSex(java.lang.String sex) {
		this.sex = sex;
	}

	public Registration(java.lang.String city, java.lang.String street,
			java.lang.String email, java.lang.String name,
			java.lang.String surname, java.lang.String password,
			java.lang.String phone, java.lang.String sex) {
		this.city = city;
		this.street = street;
		this.email = email;
		this.name = name;
		this.surname = surname;
		this.password = password;
		this.phone = phone;
		this.sex = sex;
	}

}